[package]
name = "neotron-os"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"
description = "The Neotron Operating System"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/neotron-compute/Neotron-OS"

[[bin]]
name = "flash1002"
test = false
bench = false

[[bin]]
name = "flash0802"
test = false
bench = false

[[bin]]
name = "flash0002"
test = false
bench = false

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
lto = true
debug = true
codegen-units = 1
opt-level = "s"
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
neotron-common-bios = "0.7"
r0 = "1.0"
postcard = "0.5"
serde = { version = "1.0", default-features = false }
