name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check Syntax
        run: |
          cargo check
      - name: Install Targets and Tools
        run: |
          rustup target add thumbv7em-none-eabi
          rustup target add thumbv7m-none-eabi
          rustup target add thumbv6m-none-eabi
          rustup component add llvm-tools-preview
          cargo install cargo-binutils
      - name: Build
        run: ./build.sh
      - name: Upload files to Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/thumbv6m-none-eabi-flash0002-libneotron_os.bin
            ./release/thumbv6m-none-eabi-flash0002-libneotron_os.elf
            ./release/thumbv6m-none-eabi-flash0802-libneotron_os.bin
            ./release/thumbv6m-none-eabi-flash0802-libneotron_os.elf
            ./release/thumbv6m-none-eabi-flash1002-libneotron_os.bin
            ./release/thumbv6m-none-eabi-flash1002-libneotron_os.elf
            ./release/thumbv7em-none-eabi-flash0002-libneotron_os.bin
            ./release/thumbv7em-none-eabi-flash0002-libneotron_os.elf
            ./release/thumbv7em-none-eabi-flash0802-libneotron_os.bin
            ./release/thumbv7em-none-eabi-flash0802-libneotron_os.elf
            ./release/thumbv7em-none-eabi-flash1002-libneotron_os.bin
            ./release/thumbv7em-none-eabi-flash1002-libneotron_os.elf
            ./release/thumbv7m-none-eabi-flash0002-libneotron_os.bin
            ./release/thumbv7m-none-eabi-flash0002-libneotron_os.elf
            ./release/thumbv7m-none-eabi-flash0802-libneotron_os.bin
            ./release/thumbv7m-none-eabi-flash0802-libneotron_os.elf
            ./release/thumbv7m-none-eabi-flash1002-libneotron_os.bin
            ./release/thumbv7m-none-eabi-flash1002-libneotron_os.elf
            ./release/x86_64-unknown-linux-gnu-libneotron_os.so
